<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\auth-background-key.png" />
    <None Remove="Resources\Images\auth-background.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm"/>
    <PackageReference Include="Microsoft.Extensions.Configuration"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf"/>
    <PackageReference Include="SharpVectors.Wpf"/>
	  <PackageReference Include="Crossdyne.Security.Configuration"/>
	  <PackageReference Include="Crossdyne.Security.Srp.Client"/>
    <PackageReference Include="Crossdyne.Security.Windows"/>
    <PackageReference Include="Crossdyne.Security.Cryptography"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\clients\Api\EnigmaVault.Authentication.ApiClient\EnigmaVault.Authentication.ApiClient.csproj" />
    <ProjectReference Include="..\..\clients\Api\EnigmaVault.SecretService.ApiClient\EnigmaVault.PasswordService.ApiClient\EnigmaVault.PasswordService.ApiClient.csproj" />
    <ProjectReference Include="..\..\common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\common\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\auth-background-key.png" />
    <Resource Include="Resources\Images\auth-background.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="apiconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
