<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\..\common\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
