<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper"/>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\contracts\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\shared\observability\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\EnigmaVault.Secret.Service.Domain\EnigmaVault.Secret.Service.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>EnigmaVault.Secret.Service.Application</RootNamespace>
    <AssemblyName>EnigmaVault.Secret.Service.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EnigmaVault.Secret.Service.Integration.Tests" />
  </ItemGroup>

</Project>
