<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4a2d21db-e6dd-4e15-a769-2b68712c3e0f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\common\Common.Core\Common.Core.csproj" />
    <ProjectReference Include="..\..\..\common\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\EnigmaVault.ConfigurationService.Application\EnigmaVault.ConfigurationService.Application.csproj" />
    <ProjectReference Include="..\EnigmaVault.ConfigurationService.Infrastructure\EnigmaVault.ConfigurationService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
