<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Crossdyne.Toolkit" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\core\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\shared\infrastructure\Shared.Http\Shared.Http.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>EnigmaVault.FileService.Client</RootNamespace>
    <AssemblyName>EnigmaVault.FileService.Client</AssemblyName>
  </PropertyGroup>

</Project>
